public class PlantTreeResponse
{
@InvocableVariable
public String Message;

@InvocableVariable
public String RawResponse;

@InvocableVariable
public String uuid;

@InvocableVariable
public String createdString;

@InvocableVariable
public Date createdDate;

@InvocableVariable
public Integer treeCount;

@InvocableVariable
public String enterpriseId;

@InvocableVariable
public String projectId;

@InvocableVariable
public String user;
}